version: '3.8'
name: board-api
services:
  mysql:
    image: mysql:8.0.34
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD: board
    ports:
      - 3306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
